import { useMutation, useQuery } from '@tanstack/react-query'
import { Archive, Database, Download, HardDrive, Radio, ShieldCheck, WifiOff } from 'lucide-react'
import { api } from '../api/client'
import { ErrorState, LoadingState } from '../components/AsyncState'
import { StatusBadge } from '../components/StatusBadge'

export function SettingsPage() {
  const settings = useQuery({ queryKey: ['settings'], queryFn: api.settings })
  const doctor = useQuery({ queryKey: ['doctor'], queryFn: api.doctor })
  const backup = useMutation({ mutationFn: api.backup })
  const exportData = useMutation({ mutationFn: api.exportData })
  const error = settings.error ?? doctor.error
  return <div className="page settings-page"><header className="page-header"><div><h1>Settings</h1><p>Local runtime, provider, safety, and backup state.</p></div></header>{error ? <ErrorState error={error} /> : null}{settings.isLoading || doctor.isLoading ? <LoadingState /> : null}{settings.data ? <div className="settings-layout"><section className="panel settings-section"><header><h2><HardDrive aria-hidden="true" />Local storage</h2></header><dl className="settings-list"><div><dt><Database aria-hidden="true" />Database path</dt><dd><code>{settings.data.database_path}</code></dd></div><div><dt><Archive aria-hidden="true" />Backup path</dt><dd><code>{settings.data.backup_path}</code></dd></div><div><dt><Radio aria-hidden="true" />MCP server</dt><dd><StatusBadge status="PASS" /> {settings.data.mcp_status}</dd></div><div><dt><WifiOff aria-hidden="true" />Provider</dt><dd>{settings.data.provider_status} · FTS5 fallback active</dd></div><div><dt><ShieldCheck aria-hidden="true" />Telemetry</dt><dd>{settings.data.telemetry ? 'Enabled' : 'Disabled'}</dd></div></dl></section><section className="panel settings-section"><header><h2><ShieldCheck aria-hidden="true" />Doctor</h2><StatusBadge status={doctor.data?.overall ?? 'WARN'} /></header><ul className="doctor-list">{doctor.data?.checks.map((check) => <li key={check.name}><StatusBadge status={check.status} /><span><strong>{check.name.replaceAll('_', ' ')}</strong><small>{check.detail}</small></span></li>)}</ul></section><section className="panel settings-section backup-section"><header><h2><Archive aria-hidden="true" />Backup &amp; export</h2></header><p>Create a versioned SQLite backup or a schema-validated portable JSONL export.</p><div><button className="button primary" type="button" disabled={backup.isPending} onClick={() => backup.mutate()}><Archive aria-hidden="true" />{backup.isPending ? 'Creating…' : 'Create backup'}</button><button className="button secondary" type="button" disabled={exportData.isPending} onClick={() => exportData.mutate()}><Download aria-hidden="true" />{exportData.isPending ? 'Exporting…' : 'Export JSONL'}</button></div>{backup.data ? <p className="success-message" role="status">Backup saved to <code>{backup.data.path}</code></p> : null}{exportData.data ? <p className="success-message" role="status">Export saved to <code>{exportData.data.path}</code></p> : null}{backup.error || exportData.error ? <p className="form-error" role="alert">{backup.error?.message ?? exportData.error?.message}</p> : null}</section></div> : null}</div>
}
